trigger:
- master

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy'
  pool:
    vmImage: 'ubuntu-latest'
    
  steps:
  - checkout: self  # Deze taak haalt de broncode van de huidige repository op
  - script: |
     npm install && npm run build
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'npm install and build'

  - task: ArchiveFiles@2
    inputs:
     rootFolderOrFile: '$(System.DefaultWorkingDirectory)' # or specify the path to the folder you want to zip
     includeRootFolder: false
     archiveType: 'zip'
     archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip' # specify the desired zip file name and path
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure for Students(289bd2d1-b3e3-415a-98c1-210d50fa0ad7)'
      appType: 'webAppLinux'
      WebAppName: 'iserstrapi'
      deployToSlotOrASE: true
      ResourceGroupName: 'ISERResourcegroup'
      SlotName: 'production'
      packageForLinux: '$(System.DefaultWorkingDirectory)/drop.zip'
      RuntimeStack: 'NODE|18-lts'
      StartupCommand: 'node node_modules/@strapi/strapi/bin/strapi.js start'

